default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: biome-format
        name: biome format
        entry: pnpm exec biome check --write --formatter-enabled=true --linter-enabled=false --assist-enabled=false --no-errors-on-unmatched
        language: system
        files: \.(js|cjs|mjs|ts|tsx|json|jsonc|css)$
      - id: prettier-format
        name: prettier format
        entry: pnpm exec prettier --write --ignore-unknown
        language: system
        files: \.(md|yml|yaml)$
      - id: gofmt
        name: gofmt
        entry: gofmt -w
        language: system
        files: \.go$
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: commitlint --edit
        language: node
        additional_dependencies:
          - "@commitlint/cli@20.1.0"
          - "@commitlint/config-conventional@20.0.0"
        stages:
          - commit-msg
        pass_filenames: true
        always_run: true
